# Generated by Django 6.0.1 on 2026-04-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
